In [1]:
import pandas as pd

In [3]:
df = pd.read_csv("../Load_data/DataSet_DummiesTS.csv")
df.head()

,character,max_hp,entering_hp,damage_taken,enemies,A Thousand Cuts,A Thousand Cuts+1,Accuracy,Accuracy+1,Acrobatics,...,TwistedFunnel,Unceasing Top,Vajra,Velvet Choker,WarpedTongs,Whetstone,White Beast Statue,WingedGreaves,WristBlade,level_asc_floor
0,THE_SILENT,77,77,0,21,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,5
1,THE_SILENT,77,77,1,44,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,7
2,THE_SILENT,77,61,20,18,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,12
3,THE_SILENT,77,64,2,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,19
4,THE_SILENT,77,62,6,19,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,21

In [4]:
df.drop(columns=["character"], inplace=True)

In [ ]:
# juntar enemigos por rarezas, separar floor y ascension